owner: turnkey-status
repo: upptime

sites:
  - name: TurnKey Hub
    url: https://hub.turnkeylinux.org
  - name: TurnKey Linux website
    url: https://www.turnkeylinux.org
  - name: TurnKey Linux apt repo
    url: http://archive.turnkeylinux.org
  - name: TurnKey Linux release metadata
    url: https://releases.turnkeylinux.org

assignees:
  - JedMeister

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/turnkey-status/upptime/master/assets/TurnKey-logo-white-on-transparent.png
  name: TurnKey Status
  introTitle: TurnKey GNU/Linux status page, using **real-time** data from [GitHub repository](https://github.com/turnkey-status/upptime).
  introMessage: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/turnkey-status/upptime
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
